cc = "gcc"
im = "convert"
lib_dir = "./lib/"
include_dir = "./include/"
c_dir = "./bin/"
template_dir = "./templates/"
content_dir = "./content/"
output_dir = "./out/"
copy_year = 2025
root_url = "https://lachrymal.net/"
thumbnails_dir = "thumbnails/"
template_fn = "template.html"
default_thumb = "default.png"
prelude_path = "prelude.c"
font_fn = "lmroman10-regular.otf"
